export { default as TouchScreenTest } from './TouchScreenTest/TouchScreenTest'
export { default as PixelesTest } from './PixelsTest/PixelesTest'
export { default as TouchPadTest } from './TouchPad/TouchPadTest'
export { default as WebCamTest } from './WebCamTest/WebCamTest'
export { default as AudioTest } from './AudioTest/AudioTest'
export { default as KeyBoardTest } from './KeyBoardTest/KeyBoardTest'
